CREATE TABLE COUNTRY(
    COUNTRYID INT PRIMARY KEY AUTO_INCREMENT,
    COUNTRYNAME TEXT,
    CURRENCY TEXT,
    "POPULATION" INT,
    LATITUDE TEXT,
    LONGITUDE TEXT
);
CREATE TABLE CITY(
    CITYID INT PRIMARY KEY AUTO_INCREMENT,
    CITYNAME TEXT,
    "POPULATION" INT,
    LATITUDE TEXT,
    LONGITUDE TEXT,
    COUNTRYID INT,
    FOREIGN KEY (COUNTRYID) REFERENCES COUNTRY(COUNTRYID) ON DELETE CASCADE
);